BaseUrl= "http://weremoose.github.io/dryas/"
LanguageCode= "gr-GR"
Title= "δρυάς"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "Copyright ©2016 Σωματείο Μη Κερδοσκοπικό | Σ.Σ. Τεμπών | Τ.Κ. 40004 – Γόννοι | τηλ.: 24950 93380 "
canonifyurls = true
theme = "casper"
publishdir = "public"

[params]
  description = "σωματείο για το περιβάλλον και τον πολιτισμό"
  cover = "images/cover.png"
  author = "δρυάς"
  bio= "Η δρυάς έχει δημιουργήσεi στα κτίσματα του σιδηροδρομικού σταθμού των Τεμπών ένα Κέντρο Ενημέρωσης για το περιβάλλον και τον πολιτισμό. Η θέση του είναι μοναδική και ιδανική για την ανάδειξη της ευρύτερης περιοχής που εκτείνεται από την κοιλάδα των Τεμπών ως τις παρυφές του Ολύμπου, τις ανατολικές πλαγιές του Κισσάβου και τις εκβολές του Πηνειου ποταμού στο Αιγαίο."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  # githubName = ""
  # twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true

  [[menu.main]]
    name = "Νέα"
    weight = -120
    identifier = "blog"
    url = "/"

  [[menu.main]]
    name = "Το σωματείο"
    weight = -110
    identifier = "about"
    url = "/about"

  [[menu.main]]
    name = "Η περιοχή"
    weight = -100
    identifier = "perioxi"
    url = "/koilada_tempon"

  [[menu.main]]
    name = "Eπικοινωνία"
    weight = -90
    identifier = "contact"
    url = "/contact"
